### PR TITLE
Added Authentication Controller and utility methods for handling user…

### PR DESCRIPTION
**Pull request by jessicadove**
Created an Authentication Controller to verify user credentials and added utility methods for working with user sessions. Also fixed the errors I was getting in User Model and User Repository. It may look like I added/deleted code in those two files, but I did not. Turned out there was nothing wrong with my code  : )

### CODE REVIEW

**Comment by julialoftin** [comment]
It looks like in application.properties, spring.datasource.url is set to a postgresql database instead of a mysql database, so I am getting an error. Your AuthenticationController and User Model looks good!

**Comment by jessicadove** [comment]
Made the mysql changed @julialoftin commented on above. Only thing changed : )

**Comment by jessicadove** [comment]
@julialoftin  This should be ready to be merged now

**Review by julialoftin — APPROVED** [review]
Looks excellent!

**Pull request merged**
